name: Deploy Nutva Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -p 2245 -o StrictHostKeyChecking=no ntva@demo.nutva.uz << 'EOF'
            cd ~/NutvaFrontend &&
            git fetch origin main &&
            git checkout main &&
            git pull origin main &&
            npm install &&
            npm run build &&
            pm2 reload nutva-frontend --update-env || pm2 start npm --name nutva-frontend -- run start
          EOF
